### ISSUE TITLE
Do not use Jackson

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/draft-guide-log4j#12]
Consider alternative like JSON-B or whatever is appropriate.

There is a known security vulnerability with com.fasterxml.jackson.core:jackson-databind >= 2.9.0, < 2.9.5.

**Comment by yeekangc** [comment]
@fwji, will you be able to make a quick fix for this?

**Comment by fwji** [comment]
Jackson databind is used by log4j JsonLayout class configured in the log4j configuration file. It's used as a demostration that some log4j configuration requires additional maven dependencies to be installed even though it's not explicitly used in the code.

**Comment by yeekangc** [comment]
Fixing in #13.
